export const GetGroup = {
  success: true,
  errorCode: null,
  message: null,
  total: null,
  data: [
    {
      type: "hot",
      name: "热门",
      icon: "hot.png",
      lotteries: [
        {
          type: "lhc",
          name: "香港六合彩",
          icon: "lhc.png",
          stages: 3,
          tagClass: "hot",
          lotteryTime: {
            isEnabled: true,
            isOpen: false,
            dates: "----",
            openTime: "0001-01-01 00:00:00",
            closeTime: "0001-01-01 00:00:00",
            lastNo: null,
            day: null,
            secondsRemaining: -63842013198,
            timeRemaining: "33:18",
          },
        },
        {
          type: "amlhc",
          name: "澳门六合彩",
          icon: "amlhc.png",
          stages: 7,
          tagClass: "hot",
          lotteryTime: {
            isEnabled: true,
            isOpen: true,
            dates: "2024028",
            openTime: "2024-01-27 12:00:00",
            closeTime: "2024-01-28 09:20:00",
            lastNo: "2024027",
            day: "2024-01-28",
            secondsRemaining: 17201,
            timeRemaining: "04:46:41",
          },
        },
        {
          type: "jsYxx",
          name: "极速鱼虾蟹",
          icon: "jsYxx.png",
          stages: 43200,
          tagClass: "hot",
          lotteryTime: {
            isEnabled: true,
            isOpen: true,
            dates: "0",
            openTime: "2024-01-28 00:00:00",
            closeTime: "2024-01-28 23:59:59",
            lastNo: null,
            day: "2024-01-28",
            secondsRemaining: 70000,
            timeRemaining: "19:26:40",
          },
        },
      ],
    },
    {
      type: "Mark6",
      name: "六合彩",
      icon: "Mark6.png",
      lotteries: [
        {
          type: "lhc",
          name: "香港六合彩",
          icon: "lhc.png",
          stages: 3,
          tagClass: "hot",
          lotteryTime: {
            isEnabled: true,
            isOpen: false,
            dates: "----",
            openTime: "0001-01-01 00:00:00",
            closeTime: "0001-01-01 00:00:00",
            lastNo: null,
            day: null,
            secondsRemaining: -63842013198,
            timeRemaining: "33:18",
          },
        },
        {
          type: "jslhc",
          name: "极速六合彩",
          icon: "jslhc.png",
          stages: 43200,
          tagClass: "-",
          lotteryTime: {
            isEnabled: true,
            isOpen: true,
            dates: "0",
            openTime: "2024-01-28 00:00:00",
            closeTime: "2024-01-28 23:59:59",
            lastNo: null,
            day: "2024-01-28",
            secondsRemaining: 70000,
            timeRemaining: "19:26:40",
          },
        },
        {
          type: "amlhc2",
          name: "新澳门六合彩",
          icon: "amlhc2.png",
          stages: 7,
          tagClass: "new",
          lotteryTime: {
            isEnabled: true,
            isOpen: true,
            dates: "2024028",
            openTime: "2024-01-27 12:00:00",
            closeTime: "2024-01-28 09:20:00",
            lastNo: "2024027",
            day: "2024-01-28",
            secondsRemaining: 17201,
            timeRemaining: "04:46:41",
          },
        },
        {
          type: "fflhc",
          name: "分分六合彩",
          icon: "fflhc.png",
          stages: 1440,
          tagClass: "-",
          lotteryTime: {
            isEnabled: true,
            isOpen: true,
            dates: "0273",
            openTime: "2024-01-28 04:32:00",
            closeTime: "2024-01-28 04:33:00",
            lastNo: "0272",
            day: "2024-01-28",
            secondsRemaining: -18,
            timeRemaining: "00:18",
          },
        },
        {
          type: "sflhc",
          name: "三分六合彩",
          icon: "sflhc.png",
          stages: 480,
          tagClass: "-",
          lotteryTime: {
            isEnabled: true,
            isOpen: true,
            dates: "091",
            openTime: "2024-01-28 04:30:00",
            closeTime: "2024-01-28 04:33:00",
            lastNo: "090",
            day: "2024-01-28",
            secondsRemaining: -18,
            timeRemaining: "00:18",
          },
        },
        {
          type: "amlhc",
          name: "澳门六合彩",
          icon: "amlhc.png",
          stages: 7,
          tagClass: "hot",
          lotteryTime: {
            isEnabled: true,
            isOpen: true,
            dates: "2024028",
            openTime: "2024-01-27 12:00:00",
            closeTime: "2024-01-28 09:20:00",
            lastNo: "2024027",
            day: "2024-01-28",
            secondsRemaining: 17201,
            timeRemaining: "04:46:41",
          },
        },
        {
          type: "wflhc",
          name: "五分六合彩",
          icon: "wflhc.png",
          stages: 288,
          tagClass: "-",
          lotteryTime: {
            isEnabled: true,
            isOpen: true,
            dates: "055",
            openTime: "2024-01-28 04:30:00",
            closeTime: "2024-01-28 04:35:00",
            lastNo: "054",
            day: "2024-01-28",
            secondsRemaining: 101,
            timeRemaining: "01:41",
          },
        },
      ],
    },
    {
      type: "Lucky3",
      name: "幸运3",
      icon: "Lucky3.png",
      lotteries: [
        {
          type: "sfLucky3",
          name: "三分幸运3",
          icon: "sfLucky3.png",
          stages: 480,
          tagClass: "",
          lotteryTime: {
            isEnabled: true,
            isOpen: true,
            dates: "091",
            openTime: "2024-01-28 04:30:00",
            closeTime: "2024-01-28 04:33:00",
            lastNo: "090",
            day: "2024-01-28",
            secondsRemaining: -18,
            timeRemaining: "00:18",
          },
        },
        {
          type: "ffLucky3",
          name: "分分幸运3",
          icon: "ffLucky3.png",
          stages: 1440,
          tagClass: "-",
          lotteryTime: {
            isEnabled: true,
            isOpen: true,
            dates: "0273",
            openTime: "2024-01-28 04:32:00",
            closeTime: "2024-01-28 04:33:00",
            lastNo: "0272",
            day: "2024-01-28",
            secondsRemaining: -18,
            timeRemaining: "00:18",
          },
        },
        {
          type: "wfLucky3",
          name: "五分幸运3",
          icon: "wfLucky3.png",
          stages: 288,
          tagClass: "",
          lotteryTime: {
            isEnabled: true,
            isOpen: true,
            dates: "055",
            openTime: "2024-01-28 04:30:00",
            closeTime: "2024-01-28 04:35:00",
            lastNo: "054",
            day: "2024-01-28",
            secondsRemaining: 101,
            timeRemaining: "01:41",
          },
        },
        {
          type: "shifLucky3",
          name: "十分幸运3",
          icon: "shifLucky3.png",
          stages: 144,
          tagClass: "-",
          lotteryTime: {
            isEnabled: true,
            isOpen: true,
            dates: "028",
            openTime: "2024-01-28 04:30:00",
            closeTime: "2024-01-28 04:40:00",
            lastNo: "027",
            day: "2024-01-28",
            secondsRemaining: 401,
            timeRemaining: "06:41",
          },
        },
        {
          type: "jsLucky3",
          name: "极速幸运3",
          icon: "jsLucky3.png",
          stages: 43200,
          tagClass: "",
          lotteryTime: {
            isEnabled: true,
            isOpen: true,
            dates: "0",
            openTime: "2024-01-28 00:00:00",
            closeTime: "2024-01-28 23:59:59",
            lastNo: null,
            day: "2024-01-28",
            secondsRemaining: 70000,
            timeRemaining: "19:26:40",
          },
        },
      ],
    },
    {
      type: "Yxx",
      name: "鱼虾蟹",
      icon: "Yxx.png",
      lotteries: [
        {
          type: "sfYxx",
          name: "三分鱼虾蟹",
          icon: "sfYxx.png",
          stages: 480,
          tagClass: "",
          lotteryTime: {
            isEnabled: true,
            isOpen: true,
            dates: "091",
            openTime: "2024-01-28 04:30:00",
            closeTime: "2024-01-28 04:33:00",
            lastNo: "090",
            day: "2024-01-28",
            secondsRemaining: -18,
            timeRemaining: "00:18",
          },
        },
        {
          type: "wfYxx",
          name: "五分鱼虾蟹",
          icon: "wfYxx.png",
          stages: 288,
          tagClass: null,
          lotteryTime: {
            isEnabled: true,
            isOpen: true,
            dates: "055",
            openTime: "2024-01-28 04:30:00",
            closeTime: "2024-01-28 04:35:00",
            lastNo: "054",
            day: "2024-01-28",
            secondsRemaining: 101,
            timeRemaining: "01:41",
          },
        },
        {
          type: "ffYxx",
          name: "分分鱼虾蟹",
          icon: "ffYxx.png",
          stages: 1440,
          tagClass: "-",
          lotteryTime: {
            isEnabled: true,
            isOpen: true,
            dates: "0273",
            openTime: "2024-01-28 04:32:00",
            closeTime: "2024-01-28 04:33:00",
            lastNo: "0272",
            day: "2024-01-28",
            secondsRemaining: -18,
            timeRemaining: "00:18",
          },
        },
        {
          type: "jsYxx",
          name: "极速鱼虾蟹",
          icon: "jsYxx.png",
          stages: 43200,
          tagClass: "hot",
          lotteryTime: {
            isEnabled: true,
            isOpen: true,
            dates: "0",
            openTime: "2024-01-28 00:00:00",
            closeTime: "2024-01-28 23:59:59",
            lastNo: null,
            day: "2024-01-28",
            secondsRemaining: 70000,
            timeRemaining: "19:26:40",
          },
        },
      ],
    },
    {
      type: "SeDie",
      name: "色碟",
      icon: "SeDie.png",
      lotteries: [
        {
          type: "sfSeDie",
          name: "三分色碟",
          icon: "sfSeDie.png",
          stages: 480,
          tagClass: null,
          lotteryTime: {
            isEnabled: true,
            isOpen: true,
            dates: "091",
            openTime: "2024-01-28 04:30:00",
            closeTime: "2024-01-28 04:33:00",
            lastNo: "090",
            day: "2024-01-28",
            secondsRemaining: -18,
            timeRemaining: "00:18",
          },
        },
        {
          type: "wfSeDie",
          name: "五分色碟",
          icon: "wfSeDie.png",
          stages: 288,
          tagClass: null,
          lotteryTime: {
            isEnabled: true,
            isOpen: true,
            dates: "055",
            openTime: "2024-01-28 04:30:00",
            closeTime: "2024-01-28 04:35:00",
            lastNo: "054",
            day: "2024-01-28",
            secondsRemaining: 101,
            timeRemaining: "01:41",
          },
        },
        {
          type: "jsSeDie",
          name: "极速色碟",
          icon: "jsSeDie.png",
          stages: 43200,
          tagClass: "",
          lotteryTime: {
            isEnabled: true,
            isOpen: true,
            dates: "0",
            openTime: "2024-01-28 00:00:00",
            closeTime: "2024-01-28 23:59:59",
            lastNo: null,
            day: "2024-01-28",
            secondsRemaining: 70000,
            timeRemaining: "19:26:40",
          },
        },
        {
          type: "ffSeDie",
          name: "分分色碟",
          icon: "ffSeDie.png",
          stages: 1440,
          tagClass: "-",
          lotteryTime: {
            isEnabled: true,
            isOpen: true,
            dates: "0273",
            openTime: "2024-01-28 04:32:00",
            closeTime: "2024-01-28 04:33:00",
            lastNo: "0272",
            day: "2024-01-28",
            secondsRemaining: -18,
            timeRemaining: "00:18",
          },
        },
      ],
    },
    {
      type: "Rps",
      name: "石头剪刀布",
      icon: "Rps.png",
      lotteries: [
        {
          type: "sfRps",
          name: "三分猜拳",
          icon: "sfRps.png",
          stages: 480,
          tagClass: "",
          lotteryTime: {
            isEnabled: true,
            isOpen: true,
            dates: "091",
            openTime: "2024-01-28 04:30:00",
            closeTime: "2024-01-28 04:33:00",
            lastNo: "090",
            day: "2024-01-28",
            secondsRemaining: -18,
            timeRemaining: "00:18",
          },
        },
        {
          type: "wfRps",
          name: "五分猜拳",
          icon: "wfRps.png",
          stages: 288,
          tagClass: "",
          lotteryTime: {
            isEnabled: true,
            isOpen: true,
            dates: "055",
            openTime: "2024-01-28 04:30:00",
            closeTime: "2024-01-28 04:35:00",
            lastNo: "054",
            day: "2024-01-28",
            secondsRemaining: 101,
            timeRemaining: "01:41",
          },
        },
        {
          type: "jsRps",
          name: "极速猜拳",
          icon: "jsRps.png",
          stages: 43200,
          tagClass: "",
          lotteryTime: {
            isEnabled: true,
            isOpen: true,
            dates: "0",
            openTime: "2024-01-28 00:00:00",
            closeTime: "2024-01-28 23:59:59",
            lastNo: null,
            day: "2024-01-28",
            secondsRemaining: 70000,
            timeRemaining: "19:26:40",
          },
        },
        {
          type: "ffRps",
          name: "分分猜拳",
          icon: "ffRps.png",
          stages: 1440,
          tagClass: "-",
          lotteryTime: {
            isEnabled: true,
            isOpen: true,
            dates: "0273",
            openTime: "2024-01-28 04:32:00",
            closeTime: "2024-01-28 04:33:00",
            lastNo: "0272",
            day: "2024-01-28",
            secondsRemaining: -18,
            timeRemaining: "00:18",
          },
        },
      ],
    },
    {
      type: "SicBo",
      name: "骰宝",
      icon: "SicBo.png",
      lotteries: [
        {
          type: "sfSicBo",
          name: "三分骰宝",
          icon: "sfSicBo.png",
          stages: 480,
          tagClass: null,
          lotteryTime: {
            isEnabled: true,
            isOpen: true,
            dates: "091",
            openTime: "2024-01-28 04:30:00",
            closeTime: "2024-01-28 04:33:00",
            lastNo: "090",
            day: "2024-01-28",
            secondsRemaining: -18,
            timeRemaining: "00:18",
          },
        },
        {
          type: "wfSicBo",
          name: "五分骰宝",
          icon: "wfSicBo.png",
          stages: 288,
          tagClass: null,
          lotteryTime: {
            isEnabled: true,
            isOpen: true,
            dates: "055",
            openTime: "2024-01-28 04:30:00",
            closeTime: "2024-01-28 04:35:00",
            lastNo: "054",
            day: "2024-01-28",
            secondsRemaining: 101,
            timeRemaining: "01:41",
          },
        },
        {
          type: "shifSicBo",
          name: "十分骰宝",
          icon: "shifSicBo.png",
          stages: 144,
          tagClass: "-",
          lotteryTime: {
            isEnabled: true,
            isOpen: true,
            dates: "028",
            openTime: "2024-01-28 04:30:00",
            closeTime: "2024-01-28 04:40:00",
            lastNo: "027",
            day: "2024-01-28",
            secondsRemaining: 401,
            timeRemaining: "06:41",
          },
        },
        {
          type: "jsSicBo",
          name: "极速骰宝",
          icon: "jsSicBo.png",
          stages: 43200,
          tagClass: "",
          lotteryTime: {
            isEnabled: true,
            isOpen: true,
            dates: "0",
            openTime: "2024-01-28 00:00:00",
            closeTime: "2024-01-28 23:59:59",
            lastNo: null,
            day: "2024-01-28",
            secondsRemaining: 70000,
            timeRemaining: "19:26:40",
          },
        },
        {
          type: "ffSicBo",
          name: "分分骰宝",
          icon: "ffSicBo.png",
          stages: 1440,
          tagClass: "-",
          lotteryTime: {
            isEnabled: true,
            isOpen: true,
            dates: "0273",
            openTime: "2024-01-28 04:32:00",
            closeTime: "2024-01-28 04:33:00",
            lastNo: "0272",
            day: "2024-01-28",
            secondsRemaining: -18,
            timeRemaining: "00:18",
          },
        },
      ],
    },
    {
      type: "K3",
      name: "快3",
      icon: "K3.png",
      lotteries: [
        {
          type: "sfK3",
          name: "三分快3",
          icon: "sfK3.png",
          stages: 480,
          tagClass: "-",
          lotteryTime: {
            isEnabled: true,
            isOpen: true,
            dates: "091",
            openTime: "2024-01-28 04:30:00",
            closeTime: "2024-01-28 04:33:00",
            lastNo: "090",
            day: "2024-01-28",
            secondsRemaining: -18,
            timeRemaining: "00:18",
          },
        },
        {
          type: "wfK3",
          name: "五分快3",
          icon: "wfK3.png",
          stages: 288,
          tagClass: "-",
          lotteryTime: {
            isEnabled: true,
            isOpen: true,
            dates: "055",
            openTime: "2024-01-28 04:30:00",
            closeTime: "2024-01-28 04:35:00",
            lastNo: "054",
            day: "2024-01-28",
            secondsRemaining: 101,
            timeRemaining: "01:41",
          },
        },
        {
          type: "shifK3",
          name: "十分快3",
          icon: "shifK3.png",
          stages: 144,
          tagClass: "-",
          lotteryTime: {
            isEnabled: true,
            isOpen: true,
            dates: "028",
            openTime: "2024-01-28 04:30:00",
            closeTime: "2024-01-28 04:40:00",
            lastNo: "027",
            day: "2024-01-28",
            secondsRemaining: 401,
            timeRemaining: "06:41",
          },
        },
        {
          type: "ffK3",
          name: "分分快3",
          icon: "ffK3.png",
          stages: 1440,
          tagClass: "-",
          lotteryTime: {
            isEnabled: true,
            isOpen: true,
            dates: "0273",
            openTime: "2024-01-28 04:32:00",
            closeTime: "2024-01-28 04:33:00",
            lastNo: "0272",
            day: "2024-01-28",
            secondsRemaining: -18,
            timeRemaining: "00:18",
          },
        },
        {
          type: "jsK3",
          name: "极速快3",
          icon: "jsK3.png",
          stages: 43200,
          tagClass: "-",
          lotteryTime: {
            isEnabled: true,
            isOpen: true,
            dates: "0",
            openTime: "2024-01-28 00:00:00",
            closeTime: "2024-01-28 23:59:59",
            lastNo: null,
            day: "2024-01-28",
            secondsRemaining: 70000,
            timeRemaining: "19:26:40",
          },
        },
      ],
    },
    {
      type: "PK10",
      name: "PK拾",
      icon: "PK10.png",
      lotteries: [
        {
          type: "ffPK10",
          name: "分分PK10",
          icon: "ffPK10.png",
          stages: 1440,
          tagClass: "-",
          lotteryTime: {
            isEnabled: true,
            isOpen: true,
            dates: "0273",
            openTime: "2024-01-28 04:32:00",
            closeTime: "2024-01-28 04:33:00",
            lastNo: "0272",
            day: "2024-01-28",
            secondsRemaining: -18,
            timeRemaining: "00:18",
          },
        },
        {
          type: "sfPK10",
          name: "三分PK10",
          icon: "sfPK10.png",
          stages: 480,
          tagClass: "-",
          lotteryTime: {
            isEnabled: true,
            isOpen: true,
            dates: "091",
            openTime: "2024-01-28 04:30:00",
            closeTime: "2024-01-28 04:33:00",
            lastNo: "090",
            day: "2024-01-28",
            secondsRemaining: -18,
            timeRemaining: "00:18",
          },
        },
        {
          type: "wfPK10",
          name: "五分PK10",
          icon: "wfPK10.png",
          stages: 288,
          tagClass: "-",
          lotteryTime: {
            isEnabled: true,
            isOpen: true,
            dates: "055",
            openTime: "2024-01-28 04:30:00",
            closeTime: "2024-01-28 04:35:00",
            lastNo: "054",
            day: "2024-01-28",
            secondsRemaining: 101,
            timeRemaining: "01:41",
          },
        },
        {
          type: "shifPK10",
          name: "十分PK10",
          icon: "shifPK10.png",
          stages: 144,
          tagClass: "-",
          lotteryTime: {
            isEnabled: true,
            isOpen: true,
            dates: "028",
            openTime: "2024-01-28 04:30:00",
            closeTime: "2024-01-28 04:40:00",
            lastNo: "027",
            day: "2024-01-28",
            secondsRemaining: 401,
            timeRemaining: "06:41",
          },
        },
        {
          type: "jsPK10",
          name: "极速PK10",
          icon: "jsPK10.png",
          stages: 43200,
          tagClass: "-",
          lotteryTime: {
            isEnabled: true,
            isOpen: true,
            dates: "0",
            openTime: "2024-01-28 00:00:00",
            closeTime: "2024-01-28 23:59:59",
            lastNo: null,
            day: "2024-01-28",
            secondsRemaining: 70000,
            timeRemaining: "19:26:40",
          },
        },
        {
          type: "xyft",
          name: "幸运飞艇",
          icon: "xyft.png",
          stages: 180,
          tagClass: "-",
          lotteryTime: {
            isEnabled: true,
            isOpen: true,
            dates: "043",
            openTime: "2024-01-28 04:32:50",
            closeTime: "2024-01-28 04:37:50",
            lastNo: "042",
            day: "2024-01-28",
            secondsRemaining: 271,
            timeRemaining: "04:31",
          },
        },
        {
          type: "azxy10",
          name: "澳洲幸运10",
          icon: "azxy10.png",
          stages: 288,
          tagClass: "-",
          lotteryTime: {
            isEnabled: true,
            isOpen: true,
            dates: "21082997",
            openTime: "2024-01-28 04:32:40",
            closeTime: "2024-01-28 04:37:40",
            lastNo: "21082996",
            day: "2024-01-28",
            secondsRemaining: 261,
            timeRemaining: "04:21",
          },
        },
      ],
    },
    {
      type: "SSC",
      name: "时时彩",
      icon: "SSC.png",
      lotteries: [
        {
          type: "sfssc",
          name: "三分时时彩",
          icon: "sfssc.png",
          stages: 480,
          tagClass: "-",
          lotteryTime: {
            isEnabled: true,
            isOpen: true,
            dates: "091",
            openTime: "2024-01-28 04:30:00",
            closeTime: "2024-01-28 04:33:00",
            lastNo: "090",
            day: "2024-01-28",
            secondsRemaining: -18,
            timeRemaining: "00:18",
          },
        },
        {
          type: "wfssc",
          name: "五分时时彩",
          icon: "wfssc.png",
          stages: 288,
          tagClass: "-",
          lotteryTime: {
            isEnabled: true,
            isOpen: true,
            dates: "055",
            openTime: "2024-01-28 04:30:00",
            closeTime: "2024-01-28 04:35:00",
            lastNo: "054",
            day: "2024-01-28",
            secondsRemaining: 101,
            timeRemaining: "01:41",
          },
        },
        {
          type: "shifssc",
          name: "十分时时彩",
          icon: "shifssc.png",
          stages: 144,
          tagClass: "-",
          lotteryTime: {
            isEnabled: true,
            isOpen: true,
            dates: "028",
            openTime: "2024-01-28 04:30:00",
            closeTime: "2024-01-28 04:40:00",
            lastNo: "027",
            day: "2024-01-28",
            secondsRemaining: 401,
            timeRemaining: "06:41",
          },
        },
        {
          type: "ffssc",
          name: "分分时时彩",
          icon: "ffssc.png",
          stages: 1440,
          tagClass: "-",
          lotteryTime: {
            isEnabled: true,
            isOpen: true,
            dates: "0273",
            openTime: "2024-01-28 04:32:00",
            closeTime: "2024-01-28 04:33:00",
            lastNo: "0272",
            day: "2024-01-28",
            secondsRemaining: -18,
            timeRemaining: "00:18",
          },
        },
        {
          type: "jsssc",
          name: "极速时时彩",
          icon: "jsssc.png",
          stages: 43200,
          tagClass: "-",
          lotteryTime: {
            isEnabled: true,
            isOpen: true,
            dates: "0",
            openTime: "2024-01-28 00:00:00",
            closeTime: "2024-01-28 23:59:59",
            lastNo: null,
            day: "2024-01-28",
            secondsRemaining: 70000,
            timeRemaining: "19:26:40",
          },
        },
        {
          type: "azxy5",
          name: "澳洲幸运5",
          icon: "azxy5.png",
          stages: 288,
          tagClass: "-",
          lotteryTime: {
            isEnabled: true,
            isOpen: true,
            dates: "51074097",
            openTime: "2024-01-28 04:32:40",
            closeTime: "2024-01-28 04:37:40",
            lastNo: "51074096",
            day: "2024-01-28",
            secondsRemaining: 261,
            timeRemaining: "04:21",
          },
        },
        {
          type: "ynssc",
          name: "越南时时彩",
          icon: "ynssc.png",
          stages: 288,
          tagClass: "-",
          lotteryTime: {
            isEnabled: true,
            isOpen: true,
            dates: "199",
            openTime: "2024-01-28 04:29:48",
            closeTime: "2024-01-28 04:34:48",
            lastNo: "198",
            day: "2024-01-28",
            secondsRemaining: 89,
            timeRemaining: "01:29",
          },
        },
      ],
    },
    {
      type: "VNSouth",
      name: "南部越南彩",
      icon: "VNSouth.png",
      lotteries: [
        {
          type: "MNBT",
          name: "槟知",
          icon: "MNBT.png",
          stages: 1,
          tagClass: "",
          lotteryTime: {
            isEnabled: true,
            isOpen: true,
            dates: "2024-01-30",
            openTime: "2024-01-23 05:10:00",
            closeTime: "2024-01-30 05:10:00",
            lastNo: "2024-01-23",
            day: "2024-01-30",
            secondsRemaining: 175001,
            timeRemaining: "02.00:36:41",
          },
        },
        {
          type: "MNBL",
          name: "薄辽",
          icon: "MNBL.png",
          stages: 1,
          tagClass: "",
          lotteryTime: {
            isEnabled: true,
            isOpen: true,
            dates: "2024-01-30",
            openTime: "2024-01-23 05:10:00",
            closeTime: "2024-01-30 05:10:00",
            lastNo: "2024-01-23",
            day: "2024-01-30",
            secondsRemaining: 175001,
            timeRemaining: "02.00:36:41",
          },
        },
        {
          type: "sfync",
          name: "三分越南彩",
          icon: "sfync.png",
          stages: 480,
          tagClass: "-",
          lotteryTime: {
            isEnabled: true,
            isOpen: true,
            dates: "091",
            openTime: "2024-01-28 04:30:00",
            closeTime: "2024-01-28 04:33:00",
            lastNo: "090",
            day: "2024-01-28",
            secondsRemaining: -18,
            timeRemaining: "00:18",
          },
        },
        {
          type: "MNVT",
          name: "头顿",
          icon: "MNVT.png",
          stages: 1,
          tagClass: "",
          lotteryTime: {
            isEnabled: true,
            isOpen: true,
            dates: "2024-01-30",
            openTime: "2024-01-23 05:10:00",
            closeTime: "2024-01-30 05:10:00",
            lastNo: "2024-01-23",
            day: "2024-01-30",
            secondsRemaining: 175001,
            timeRemaining: "02.00:36:41",
          },
        },
        {
          type: "MNDN",
          name: "同奈",
          icon: "MNDN.png",
          stages: 1,
          tagClass: "",
          lotteryTime: {
            isEnabled: true,
            isOpen: true,
            dates: "2024-01-31",
            openTime: "2024-01-24 05:10:00",
            closeTime: "2024-01-31 05:10:00",
            lastNo: "2024-01-24",
            day: "2024-01-31",
            secondsRemaining: 261401,
            timeRemaining: "03.00:36:41",
          },
        },
        {
          type: "MNST",
          name: "朔庄",
          icon: "MNST.png",
          stages: 1,
          tagClass: "-",
          lotteryTime: {
            isEnabled: true,
            isOpen: true,
            dates: "2024-01-31",
            openTime: "2024-01-24 05:10:00",
            closeTime: "2024-01-31 05:10:00",
            lastNo: "2024-01-24",
            day: "2024-01-31",
            secondsRemaining: 261401,
            timeRemaining: "03.00:36:41",
          },
        },
        {
          type: "MNCT",
          name: "芹苴",
          icon: "MNCT.png",
          stages: 1,
          tagClass: "",
          lotteryTime: {
            isEnabled: true,
            isOpen: true,
            dates: "2024-01-31",
            openTime: "2024-01-24 05:10:00",
            closeTime: "2024-01-31 05:10:00",
            lastNo: "2024-01-24",
            day: "2024-01-31",
            secondsRemaining: 261401,
            timeRemaining: "03.00:36:41",
          },
        },
        {
          type: "MNAG",
          name: "安江",
          icon: "MNAG.png",
          stages: 1,
          tagClass: "",
          lotteryTime: {
            isEnabled: true,
            isOpen: true,
            dates: "2024-02-01",
            openTime: "2024-01-25 05:10:00",
            closeTime: "2024-02-01 05:10:00",
            lastNo: "2024-01-25",
            day: "2024-02-01",
            secondsRemaining: 347801,
            timeRemaining: "04.00:36:41",
          },
        },
        {
          type: "MNBTH",
          name: "平顺",
          icon: "MNBTH.png",
          stages: 1,
          tagClass: "",
          lotteryTime: {
            isEnabled: true,
            isOpen: true,
            dates: "2024-02-01",
            openTime: "2024-01-25 05:10:00",
            closeTime: "2024-02-01 05:10:00",
            lastNo: "2024-01-25",
            day: "2024-02-01",
            secondsRemaining: 347801,
            timeRemaining: "04.00:36:41",
          },
        },
        {
          type: "MNTN",
          name: "西宁",
          icon: "MNTN.png",
          stages: 1,
          tagClass: "",
          lotteryTime: {
            isEnabled: true,
            isOpen: true,
            dates: "2024-02-01",
            openTime: "2024-01-25 05:10:00",
            closeTime: "2024-02-01 05:10:00",
            lastNo: "2024-01-25",
            day: "2024-02-01",
            secondsRemaining: 347801,
            timeRemaining: "04.00:36:41",
          },
        },
        {
          type: "MNHCM",
          name: "胡志明市",
          icon: "MNHCM.png",
          stages: 2,
          tagClass: "-",
          lotteryTime: {
            isEnabled: true,
            isOpen: true,
            dates: "2024-01-29",
            openTime: "2024-01-27 05:10:00",
            closeTime: "2024-01-29 05:10:00",
            lastNo: "2024-01-27",
            day: "2024-01-29",
            secondsRemaining: 88601,
            timeRemaining: "01.00:36:41",
          },
        },
        {
          type: "MNCM",
          name: "金瓯",
          icon: "MNCM.png",
          stages: 1,
          tagClass: "",
          lotteryTime: {
            isEnabled: true,
            isOpen: true,
            dates: "2024-01-29",
            openTime: "2024-01-22 05:10:00",
            closeTime: "2024-01-29 05:10:00",
            lastNo: "2024-01-22",
            day: "2024-01-29",
            secondsRemaining: 88601,
            timeRemaining: "01.00:36:41",
          },
        },
        {
          type: "MNDT",
          name: "同塔",
          icon: "MNDT.png",
          stages: 1,
          tagClass: "",
          lotteryTime: {
            isEnabled: true,
            isOpen: true,
            dates: "2024-01-29",
            openTime: "2024-01-22 05:10:00",
            closeTime: "2024-01-29 05:10:00",
            lastNo: "2024-01-22",
            day: "2024-01-29",
            secondsRemaining: 88601,
            timeRemaining: "01.00:36:41",
          },
        },
        {
          type: "MNBD",
          name: "平阳",
          icon: "MNBD.png",
          stages: 1,
          tagClass: "",
          lotteryTime: {
            isEnabled: true,
            isOpen: true,
            dates: "2024-02-02",
            openTime: "2024-01-26 05:10:00",
            closeTime: "2024-02-02 05:10:00",
            lastNo: "2024-01-26",
            day: "2024-02-02",
            secondsRemaining: 434201,
            timeRemaining: "05.00:36:41",
          },
        },
        {
          type: "MNTV",
          name: "茶荣",
          icon: "MNTV.png",
          stages: 1,
          tagClass: "",
          lotteryTime: {
            isEnabled: true,
            isOpen: true,
            dates: "2024-02-02",
            openTime: "2024-01-26 05:10:00",
            closeTime: "2024-02-02 05:10:00",
            lastNo: "2024-01-26",
            day: "2024-02-02",
            secondsRemaining: 434201,
            timeRemaining: "05.00:36:41",
          },
        },
        {
          type: "MNVL",
          name: "永隆",
          icon: "MNVL.png",
          stages: 1,
          tagClass: "",
          lotteryTime: {
            isEnabled: true,
            isOpen: true,
            dates: "2024-02-02",
            openTime: "2024-01-26 05:10:00",
            closeTime: "2024-02-02 05:10:00",
            lastNo: "2024-01-26",
            day: "2024-02-02",
            secondsRemaining: 434201,
            timeRemaining: "05.00:36:41",
          },
        },
        {
          type: "MNBP",
          name: "平福",
          icon: "MNBP.png",
          stages: 1,
          tagClass: "",
          lotteryTime: {
            isEnabled: true,
            isOpen: true,
            dates: "2024-02-03",
            openTime: "2024-01-27 05:10:00",
            closeTime: "2024-02-03 05:10:00",
            lastNo: "2024-01-27",
            day: "2024-02-03",
            secondsRemaining: 520601,
            timeRemaining: "06.00:36:41",
          },
        },
        {
          type: "MNHG",
          name: "后江",
          icon: "MNHG.png",
          stages: 1,
          tagClass: "",
          lotteryTime: {
            isEnabled: true,
            isOpen: true,
            dates: "2024-02-03",
            openTime: "2024-01-27 05:10:00",
            closeTime: "2024-02-03 05:10:00",
            lastNo: "2024-01-27",
            day: "2024-02-03",
            secondsRemaining: 520601,
            timeRemaining: "06.00:36:41",
          },
        },
        {
          type: "MNLA",
          name: "隆安",
          icon: "MNLA.png",
          stages: 1,
          tagClass: "",
          lotteryTime: {
            isEnabled: true,
            isOpen: true,
            dates: "2024-02-03",
            openTime: "2024-01-27 05:10:00",
            closeTime: "2024-02-03 05:10:00",
            lastNo: "2024-01-27",
            day: "2024-02-03",
            secondsRemaining: 520601,
            timeRemaining: "06.00:36:41",
          },
        },
        {
          type: "MNKG",
          name: "坚江",
          icon: "MNKG.png",
          stages: 1,
          tagClass: "",
          lotteryTime: {
            isEnabled: true,
            isOpen: true,
            dates: "2024-01-28",
            openTime: "2024-01-21 05:10:00",
            closeTime: "2024-01-28 05:10:00",
            lastNo: "2024-01-21",
            day: "2024-01-28",
            secondsRemaining: 2201,
            timeRemaining: "36:41",
          },
        },
        {
          type: "MNTG",
          name: "前江",
          icon: "MNTG.png",
          stages: 1,
          tagClass: "",
          lotteryTime: {
            isEnabled: true,
            isOpen: true,
            dates: "2024-01-28",
            openTime: "2024-01-21 05:10:00",
            closeTime: "2024-01-28 05:10:00",
            lastNo: "2024-01-21",
            day: "2024-01-28",
            secondsRemaining: 2201,
            timeRemaining: "36:41",
          },
        },
        {
          type: "MNDL",
          name: "大叻",
          icon: "MNDL.png",
          stages: 1,
          tagClass: "",
          lotteryTime: {
            isEnabled: true,
            isOpen: true,
            dates: "2024-01-28",
            openTime: "2024-01-21 05:10:00",
            closeTime: "2024-01-28 05:10:00",
            lastNo: "2024-01-21",
            day: "2024-01-28",
            secondsRemaining: 2201,
            timeRemaining: "36:41",
          },
        },
      ],
    },
    {
      type: "kl10",
      name: "快乐十分",
      icon: "kl10.png",
      lotteries: [
        {
          type: "jsklsf",
          name: "极速快乐十分",
          icon: "jsklsf.png",
          stages: 43200,
          tagClass: "",
          lotteryTime: {
            isEnabled: true,
            isOpen: false,
            dates: "----",
            openTime: "0001-01-01 00:00:00",
            closeTime: "0001-01-01 00:00:00",
            lastNo: null,
            day: null,
            secondsRemaining: -63842013198,
            timeRemaining: "33:18",
          },
        },
      ],
    },
  ],
};

export const GetSiteConfig = {
  success: true,
  errorCode: null,
  message: null,
  total: null,
  data: {
    siteTitle: "天游游戏",
    logo: {
      homeLogo84: "/file/DEVGJ/2023/10/6/W7FXsTowNp3AoJDijgr.png",
      loginLogo84: "/file/DEVGJ/2023/1/16/KaR6tfZfHeX6yVrn5sf.png",
      logo384: null,
    },
    kfUrl: "https://t.me/robogaming002",
    kfqq: null,
    kfqqUrl: "https://t.me/skygame888",
    line: "https://line.me/ti/g/DQk-Mr_8AH",
    codeKey: "DEVGJ",
    imgPath: "https://crane3.im6ge.com",
    appDownloadUrl: "https://down.ttiossign.com/#/join/dgmTvH?lang=y",
    appDownloadQrCode:
      "iVBORw0KGgoAAAANSUhEUgAAAKQAAACkCAYAAAAZtYVBAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAv7SURBVHhe7ZLBaixJEAP9/z/99poESQdCVes2dECcpNTU2PPz7+PjRXw/yI9X8f0gP17F94P8eBXfD/LjVXw/yI9X8f0gP17F94P8eBXfD/LjVXw/yI9X8f0gP17F94P8eBXfD/LjVXw/yI9X8f0gP17F94P8eBX1D/Ln5+d/NaW9N2yf+WmN7eamLfXC9qibprT3hu0zP62x3dy0pV7YHnXTlPbesH3mpzW2m5u21Avbo26a0t4bts/8tMZ2c9OWeuH0g0i6zz4llhP2KXl73nJ6v144/SCS7rNPieWEfUrenrec3q8XTj+IpPvsU2I5YZ+St+ctp/frhdMPIuk++5RYTtin5O15y+n9esEexNwkbd5i+5YT9lsN6zM3ieUp9YI9iLlJ2rzF9i0n7Lca1mduEstT6gV7EHOTtHmL7VtO2G81rM/cJJan1Av2IOYmafMW27ecsN9qWJ+5SSxPqRfsQcxNcjo3T3N6n3uUpLlJLE+pF+xBzE1yOjdPc3qfe5SkuUksT6kX7EHMTXI6N09zep97lKS5SSxPqRfsQcxNcjo3T3N6n3uUpLlJLE+pF+xBzE3S5gbvT2tsN4mG9ZmbxPKUesEexNwkbW7w/rTGdpNoWJ+5SSxPqRfsQcxN0uYG709rbDeJhvWZm8TylHrBHsTcJG1u8P60xnaTaFifuUksT6kXTj+I2D5z00j7xO7TnJI2bzm9Xy+cfhCxfeamkfaJ3ac5JW3ecnq/Xjj9IGL7zE0j7RO7T3NK2rzl9H69cPpBxPaZm0baJ3af5pS0ecvp/XqBD7ot+fIsv21LvbA96qbky7P8ti31wvaom5Ivz/LbttQL26NuSr48y2/b0i/8MvYHaXPD7pmnEsv/On/+G9k/qM0Nu2eeSiz/6/z5b2T/oDY37J55KrH8r/Pnv5H9g9rcsHvmqcTyv079jewPxLw1xe6Zm8Z286Sx3TxJtk7jbepPsAczb02xe+amsd08aWw3T5Kt03ib+hPswcxbU+yeuWlsN08a282TZOs03qb+BHsw89YUu2duGtvNk8Z28yTZOo23uf4J25eaptg9c5NYbvA+lWydJ8nWmZKtMyWWp/QLAh9MU+yeuUksN3ifSrbOk2TrTMnWmRLLU/oFgQ+mKXbP3CSWG7xPJVvnSbJ1pmTrTInlKf2CwAfTFLtnbhLLDd6nkq3zJNk6U7J1psTylH4B2APT3CRbZ0q2zkmN7eZJsnWmhvUtP83xT7AvkOYm2TpTsnVOamw3T5KtMzWsb/lpjn+CfYE0N8nWmZKtc1Jju3mSbJ2pYX3LT3P8E+wLpLlJts6UbJ2TGtvNk2TrTA3rW36a+hP4YPrb2HuY05RtY2psN08a1mduEstT6gU+iP429h7mNGXbmBrbzZOG9ZmbxPKUeoEPor+NvYc5Tdk2psZ286RhfeYmsTylXuCD6G9j72FOU7aNqbHdPGlYn7lJLE/pF0L4BSjZOlOydaYkzU1ju5mSrZNobDdTsnWmLf1CyPYlpmTrTMnWmZI0N43tZkq2TqKx3UzJ1pm29Ash25eYkq0zJVtnStLcNLabKdk6icZ2MyVbZ9rSL4RsX2JKts6UbJ0pSXPT2G6mZOskGtvNlGydaUu9sD1qamw3U7J1pkbaJ3bPnBrbzZOnsX3mtKVe2B41NbabKdk6UyPtE7tnTo3t5snT2D5z2lIvbI+aGtvNlGydqZH2id0zp8Z28+RpbJ85bakXtkdNje1mSrbO1Ej7xO6ZU2O7efI0ts+cttQL6YPYp2TrTFu2zSnZOk8a282TxnbzJGnzlnoxfSD7lGydacu2OSVb50lju3nS2G6eJG3eUi+mD2Sfkq0zbdk2p2TrPGlsN08a282TpM1b6sX0gexTsnWmLdvmlGydJ43t5klju3mStHlLvZg+MO3fJn3P2/umsd1Mb1N/QvrgtH+b9D1v75vGdjO9Tf0J6YPT/m3S97y9bxrbzfQ29SekD077t0nf8/a+aWw309vc/wSQfkH2TWI5sX6bp9gec0q2zjSlvSf9Qkj6Bdg3ieXE+m2eYnvMKdk605T2nvQLIekXYN8klhPrt3mK7TGnZOtMU9p70i+EpF+AfZNYTqzf5im2x5ySrTNNae9JvxDCL2AaaZ/wnrZsm08abZ+SrTMllqf0CyH8AqaR9gnvacu2+aTR9inZOlNieUq/EMIvYBppn/CetmybTxptn5KtMyWWp/QLIfwCppH2Ce9py7b5pNH2Kdk6U2J5Sr9wGH7BVGJ5CvcoSXPasm0+SbbO9DTnF0u2L51ILE/hHiVpTlu2zSfJ1pme5vxiyfalE4nlKdyjJM1py7b5JNk609OcXyzZvnQisTyFe5SkOW3ZNp8kW2d6mnpxe2SjYf3bOTndZ26mbBuNp6kXt0c2Gta/nZPTfeZmyrbReJp6cXtko2H92zk53WdupmwbjaepF7dHNhrWv52T033mZsq20Xia44vpg9m/LbG8Jd2/3TfSvbRv9AsgfSD7tyWWt6T7t/tGupf2jX4BpA9k/7bE8pZ0/3bfSPfSvtEvgPSB7N+WWN6S7t/uG+le2jfqhfRB1rfc4D0lW2dKts40Jb23PnNqbDdTYnlKvZA+yPqWG7ynZOtMydaZpqT31mdOje1mSixPqRfSB1nfcoP3lGydKdk605T03vrMqbHdTInlKfVC+iDrW27wnpKtMyVbZ5qS3lufOTW2mymxPKVeSB/EPiVbZ5qS3rd9k1hO2Kct2+b0NPVi+kD2Kdk605T0vu2bxHLCPm3ZNqenqRfTB7JPydaZpqT3bd8klhP2acu2OT1NvZg+kH1Kts40Jb1v+yaxnLBPW7bN6WnqRXug5SntHu9pSnrPfuppts9obKkX7EGWp7R7vKcp6T37qafZPqOxpV6wB1me0u7xnqak9+ynnmb7jMaWesEeZHlKu8d7mpLes596mu0zGlvqBXsQc0q2zpNvw97HnJKtc1Nju5m21Av2IOaUbJ0n34a9jzklW+emxnYzbakX7EHMKdk6T74Nex9zSrbOTY3tZtpSL9iDmFOydZ58G/Y+5pRsnZsa28205X3/0RD7g1hO2KfGdpNobDfTFLtv85R+4ZexP4jlhH1qbDeJxnYzTbH7Nk/pF34Z+4NYTtinxnaTaGw30xS7b/OUfuGXsT+I5YR9amw3icZ2M02x+zZPqRf4oNumbBtPkq2TaFifuUlO5/Q09eL2yJumbBtPkq2TaFifuUlO5/Q09eL2yJumbBtPkq2TaFifuUlO5/Q09eL2yJumbBtPkq2TaFifuUlO5/Q09eL1B8o+c2q0/daUbWOasm00ttQLpx9EbJ85Ndp+a8q2MU3ZNhpb6oXTDyK2z5wabb81ZduYpmwbjS31wukHEdtnTo2235qybUxTto3GlnrBHsTcJGluGrf7hPcm2TonJVtn2lIv2IOYmyTNTeN2n/DeJFvnpGTrTFvqBXsQc5OkuWnc7hPem2TrnJRsnWlLvWAPYm6SNDeN233Ce5NsnZOSrTNtqRfsQcxNkuYm2TpTkua0xfYsJ+ybxPKUesEexNwkaW6SrTMlaU5bbM9ywr5JLE+pF+xBzE2S5ibZOlOS5rTF9iwn7JvE8pR6wR7E3CRpbpKtMyVpTltsz3LCvkksT6kX7EHMTZLmb9OwPnNqbDdTYvlt6k+0L8DcJGn+Ng3rM6fGdjMllt+m/kT7AsxNkuZv07A+c2psN1Ni+W3qT7QvwNwkaf42Deszp8Z2MyWW36b+xNtf4PQ+90xieQv3qbHdTMnWefI29SfcfvDpfe6ZxPIW7lNju5mSrfPkbepPuP3g0/vcM4nlLdynxnYzJVvnydvUn3D7waf3uWcSy1u4T43tZkq2zpO3qT9he/RNydaZGqf7lhPrMz9tSntv1It84G3J1pkap/uWE+szP21Ke2/Ui3zgbcnWmRqn+5YT6zM/bUp7b9SLfOBtydaZGqf7lhPrMz9tSntvnF/8+Cj4fpAfr+L7QX68iu8H+fEqvh/kx6v4fpAfr+L7QX68iu8H+fEqvh/kx6v4fpAfr+L7QX68iu8H+fEqvh/kx6v4fpAfr+L7QX68iu8H+fEi/v37D5hTh6hwvnSMAAAAAElFTkSuQmCC",
    resetPasswordWay: 0,
    disallowRegisterTryMember: true,
    openScrollDiaLog: false,
    shareContent: null,
    isRealTimePremium: true,
    cultures: [
      {
        name: "简体中文",
        code: "zh-CN",
        currency: "CNY",
        isDefault: true,
        isOpen: true,
      },
      {
        name: "English",
        code: "en-US",
        currency: "USD",
        isDefault: false,
        isOpen: true,
      },
      {
        name: "Tiếng Việt",
        code: "vi-VN",
        currency: "VND",
        isDefault: false,
        isOpen: true,
      },
      {
        name: "ไทย",
        code: "th-TH",
        currency: "THB",
        isDefault: false,
        isOpen: true,
      },
      {
        name: "bahasa Indonesia",
        code: "id-ID",
        currency: "IDR",
        isDefault: false,
        isOpen: true,
      },
      {
        name: "हिंदी",
        code: "hi-IN",
        currency: "INR",
        isDefault: false,
        isOpen: true,
      },
    ],
    validatorType: 1,
    isOpenEmailVerification: true,
    isOpenTelVerification: true,
    allowFreeMember: true,
    isOpenTransferByMember: false,
    isSupportSwitchLanguage: true,
  },
};

export const GameCategorys = {
  success: true,
  errorCode: null,
  message: null,
  total: null,
  data: [
    {
      name: "彩票游戏",
      code: "cp",
      tag: null,
    },
    {
      name: "真人视讯",
      code: "sx",
      tag: null,
    },
    {
      name: "体育游戏",
      code: "ty",
      tag: null,
    },
    {
      name: "棋牌游戏",
      code: "qp",
      tag: null,
    },
    {
      name: "捕鱼游戏",
      code: "by",
      tag: null,
    },
    {
      name: "电子游艺",
      code: "dz",
      tag: null,
    },
    {
      name: "电竞游戏",
      code: "dj",
      tag: null,
    },
    {
      name: "斗鸡游戏",
      code: "douji",
      tag: null,
    },
  ],
};

export const GetSlide = {
  success: true,
  errorCode: null,
  message: null,
  total: null,
  data: [
    {
      cultureCode: "zh-CN",
      cultureName: "简体中文",
      title: "2023玉兔",
      imageUrl: "/file/DEVGJ/2023/1/16/uTZTL1fZr9wwlnditVW.png",
      mobileImageUrl: "/file/DEVGJ/2023/1/16/uTZTL1fZr9wwlnditVW.png",
      linkUrl: null,
      status: true,
      createTime: "2023-01-16 01:23:11",
      orderNo: 0,
      id: 77,
      objId: "7eabd285fa714e918e2f3e256a143e8e",
    },
    {
      cultureCode: "zh-CN",
      cultureName: "简体中文",
      title: "ddd",
      imageUrl: "/file/DEVGJ/2022/12/21/RRsGE5kldAwFP1os1l8.jpg",
      mobileImageUrl: "/file/DEVGJ/2022/12/21/RRsGE5kldAwFP1os1l8.jpg",
      linkUrl: null,
      status: true,
      createTime: "1900-01-01 00:00:00",
      orderNo: 0,
      id: 72,
      objId: "e82a5732675a45fbb86c85f172990fc2",
    },
    {
      cultureCode: "zh-CN",
      cultureName: "简体中文",
      title:
        "玉兔迎春玉兔迎春玉兔迎春玉兔迎春玉兔迎春玉兔迎春玉兔迎春玉兔迎春玉兔迎春玉兔迎春玉兔迎春玉兔迎春玉啊",
      imageUrl: "/file/DEVGJ/2023/1/16/wmprsfzLgPlj5ZeAPHL.png",
      mobileImageUrl: "/file/DEVGJ/2023/1/16/wmprsfzLgPlj5ZeAPHL.png",
      linkUrl: null,
      status: true,
      createTime: "2023-01-16 01:23:36",
      orderNo: 1,
      id: 78,
      objId: "dbc56decd4e24573acead81212dc1a5f",
    },
    {
      cultureCode: "zh-CN",
      cultureName: "简体中文",
      title: "激情赛场、盛世狂欢，2022世界杯火热来袭，绿茵风采、尽在天游",
      imageUrl: "/file/DEVGJ/2022/11/9/TvFWbv1vGCzpeir413v.jpg",
      mobileImageUrl: "/file/DEVGJ/2022/11/9/TvFWbv1vGCzpeir413v.jpg",
      linkUrl: null,
      status: true,
      createTime: "1900-01-01 00:00:00",
      orderNo: 2,
      id: 55,
      objId: "d14cd3aba4f241edb4b939ffd483bca5",
    },
    {
      cultureCode: "zh-CN",
      cultureName: "简体中文",
      title: "激情赛场、盛世狂欢，2022世界杯火热来袭，绿茵风采、尽在天游",
      imageUrl: "/file/DEVGJ/2022/11/9/aAKN8cZSzYoiPUpGBzm.jpg",
      mobileImageUrl: "/file/DEVGJ/2022/11/9/aAKN8cZSzYoiPUpGBzm.jpg",
      linkUrl: null,
      status: true,
      createTime: "2022-11-09 03:55:29",
      orderNo: 3,
      id: 49,
      objId: "dc8fcddabd9a40bda9799b11fabe0195",
    },
    {
      cultureCode: "zh-CN",
      cultureName: "简体中文",
      title: null,
      imageUrl: "/file/DEVGJ/2022/3/4/2c7WUXZSQQpqSN2t0Dj.jpg",
      mobileImageUrl: "/file/DEVGJ/2022/3/4/2c7WUXZSQQpqSN2t0Dj.jpg",
      linkUrl: null,
      status: true,
      createTime: "1900-01-01 00:00:00",
      orderNo: 4,
      id: 43,
      objId: "ac0fca31c92747508ac7d44dceda371b",
    },
  ],
};

export const GetAllNotice = {
  success: true,
  errorCode: null,
  message: null,
  total: null,
  data: {
    popMsgs: [],
    scrollMsgs: [
      {
        cultureCode: "zh-CN",
        cultureName: "简体中文",
        title: "kjgjzkgjzkgjzkgjzkhjzklfz",
        content: "pokiPOfkpolvgkzlfkzlkzlgbkzldbklhkb",
        noticeType: 3,
        noticeTypeDesc: "滚动公告",
        status: 1,
        operator: "daxian",
        sortIndex: 0,
        beginTime: "2023-12-01 00:00:00",
        endTime: "2024-03-31 00:00:00",
        createTime: "2023-12-04 10:04:42",
        updateTime: null,
        id: 87,
        objId: "adea5555adcd4d1a8f49500506d2c0af",
      },
    ],
  },
};

export const GetCurrency = {
  success: true,
  errorCode: null,
  message: null,
  total: null,
  data: [
    {
      code: "CNY",
      symbol: "¥",
      denomination: "",
      name: "人民币",
      nameList: [
        {
          dataKey: "CNY",
          code: "zh-CN",
          value: "人民币",
          value1: null,
          remark: null,
          id: 1,
          objId: "a93b09c7e49811ebb5a01866da5bbebb",
        },
        {
          dataKey: "CNY",
          code: "en-US",
          value: "CNY",
          value1: null,
          remark: null,
          id: 2,
          objId: "a93b5200e49811ebb5a01866da5bbebb",
        },
        {
          dataKey: "CNY",
          code: "vi-VN",
          value: "CNY",
          value1: null,
          remark: null,
          id: 3,
          objId: "a93b9673e49811ebb5a01866da5bbebb",
        },
        {
          dataKey: "CNY",
          code: "th-TH",
          value: "CNY",
          value1: null,
          remark: null,
          id: 4,
          objId: "a93bdab5e49811ebb5a01866da5bbebb",
        },
        {
          dataKey: "CNY",
          code: "id-ID",
          value: "CNY",
          value1: null,
          remark: null,
          id: 5,
          objId: "a93c1f92e49811ebb5a01866da5bbebb",
        },
        {
          dataKey: "CNY",
          code: "hi-IN",
          value: "CNY",
          value1: null,
          remark: null,
          id: 6,
          objId: "a93c6371e49811ebb5a01866da5bbebb",
        },
      ],
      exchangeRate: "7.08440",
      exchangeRateY: 7.0844,
      isDefault: false,
      createTime: "2021-07-14 07:43:09",
      cultureCode: "zh-CN",
      gameCredit: 0.0,
      status: true,
      isShow: true,
      id: 1,
      objId: "a93a6595e49811ebb5a01866da5bbebb",
    },
    {
      code: "USD",
      symbol: "$",
      denomination: "",
      name: "美元",
      nameList: [
        {
          dataKey: "USD",
          code: "zh-CN",
          value: "美元",
          value1: null,
          remark: null,
          id: 7,
          objId: "a93ceb3fe49811ebb5a01866da5bbebb",
        },
        {
          dataKey: "USD",
          code: "en-US",
          value: "USD",
          value1: null,
          remark: null,
          id: 8,
          objId: "a93d2f89e49811ebb5a01866da5bbebb",
        },
        {
          dataKey: "USD",
          code: "vi-VN",
          value: "đô la Mỹ",
          value1: null,
          remark: null,
          id: 9,
          objId: "a93d7462e49811ebb5a01866da5bbebb",
        },
        {
          dataKey: "USD",
          code: "th-TH",
          value: "USD",
          value1: null,
          remark: null,
          id: 10,
          objId: "a93db60fe49811ebb5a01866da5bbebb",
        },
        {
          dataKey: "USD",
          code: "id-ID",
          value: "USD",
          value1: null,
          remark: null,
          id: 11,
          objId: "a93df751e49811ebb5a01866da5bbebb",
        },
        {
          dataKey: "USD",
          code: "hi-IN",
          value: "USD",
          value1: null,
          remark: null,
          id: 12,
          objId: "a93e3ae6e49811ebb5a01866da5bbebb",
        },
      ],
      exchangeRate: "1.00000",
      exchangeRateY: 1.0,
      isDefault: true,
      createTime: "2021-07-14 07:43:09",
      cultureCode: "en-US",
      gameCredit: 0.0,
      status: true,
      isShow: true,
      id: 2,
      objId: "a93ca34fe49811ebb5a01866da5bbebb",
    },
    {
      code: "VND",
      symbol: "₫",
      denomination: "k",
      name: "越南盾",
      nameList: [
        {
          dataKey: "VND",
          code: "zh-CN",
          value: "越南盾",
          value1: null,
          remark: null,
          id: 13,
          objId: "a93ec066e49811ebb5a01866da5bbebb",
        },
        {
          dataKey: "VND",
          code: "en-US",
          value: "VND",
          value1: null,
          remark: null,
          id: 14,
          objId: "a93f0507e49811ebb5a01866da5bbebb",
        },
        {
          dataKey: "VND",
          code: "vi-VN",
          value: "Đồng việt nam",
          value1: null,
          remark: null,
          id: 15,
          objId: "a93f4a72e49811ebb5a01866da5bbebb",
        },
        {
          dataKey: "VND",
          code: "th-TH",
          value: "VND",
          value1: null,
          remark: null,
          id: 16,
          objId: "a93f8faae49811ebb5a01866da5bbebb",
        },
        {
          dataKey: "VND",
          code: "id-ID",
          value: "VND",
          value1: null,
          remark: null,
          id: 17,
          objId: "a93fd94de49811ebb5a01866da5bbebb",
        },
        {
          dataKey: "VND",
          code: "hi-IN",
          value: "VND",
          value1: null,
          remark: null,
          id: 18,
          objId: "a9401b03e49811ebb5a01866da5bbebb",
        },
      ],
      exchangeRate: "24585.5",
      exchangeRateY: 24585.5,
      isDefault: false,
      createTime: "2021-07-14 07:43:09",
      cultureCode: "vi-VN",
      gameCredit: 0.0,
      status: true,
      isShow: true,
      id: 3,
      objId: "a93e7b7de49811ebb5a01866da5bbebb",
    },
    {
      code: "THB",
      symbol: "฿",
      denomination: "",
      name: "泰铢",
      nameList: [
        {
          dataKey: "THB",
          code: "zh-CN",
          value: "泰铢",
          value1: null,
          remark: null,
          id: 19,
          objId: "a9409f1ee49811ebb5a01866da5bbebb",
        },
        {
          dataKey: "THB",
          code: "en-US",
          value: "THB",
          value1: null,
          remark: null,
          id: 20,
          objId: "a940e435e49811ebb5a01866da5bbebb",
        },
        {
          dataKey: "THB",
          code: "vi-VN",
          value: "THB",
          value1: null,
          remark: null,
          id: 21,
          objId: "a941295ce49811ebb5a01866da5bbebb",
        },
        {
          dataKey: "THB",
          code: "th-TH",
          value: "THB",
          value1: null,
          remark: null,
          id: 22,
          objId: "a9416c3de49811ebb5a01866da5bbebb",
        },
        {
          dataKey: "THB",
          code: "id-ID",
          value: "THB",
          value1: null,
          remark: null,
          id: 23,
          objId: "a941ad98e49811ebb5a01866da5bbebb",
        },
        {
          dataKey: "THB",
          code: "hi-IN",
          value: "THB",
          value1: null,
          remark: null,
          id: 24,
          objId: "a941f1ace49811ebb5a01866da5bbebb",
        },
      ],
      exchangeRate: "35.6170",
      exchangeRateY: 35.617,
      isDefault: false,
      createTime: "2021-07-14 07:43:09",
      cultureCode: "th-TH",
      gameCredit: 0.0,
      status: true,
      isShow: true,
      id: 4,
      objId: "a9405bb6e49811ebb5a01866da5bbebb",
    },
    {
      code: "IDR",
      symbol: "Rp",
      denomination: "k",
      name: "印尼盾",
      nameList: [
        {
          dataKey: "IDR",
          code: "zh-CN",
          value: "印尼盾",
          value1: null,
          remark: null,
          id: 25,
          objId: "a9427f37e49811ebb5a01866da5bbebb",
        },
        {
          dataKey: "IDR",
          code: "en-US",
          value: "IDR",
          value1: null,
          remark: null,
          id: 26,
          objId: "a942c0fce49811ebb5a01866da5bbebb",
        },
        {
          dataKey: "IDR",
          code: "vi-VN",
          value: "IDR",
          value1: null,
          remark: null,
          id: 27,
          objId: "a943074fe49811ebb5a01866da5bbebb",
        },
        {
          dataKey: "IDR",
          code: "th-TH",
          value: "IDR",
          value1: null,
          remark: null,
          id: 28,
          objId: "a9434b74e49811ebb5a01866da5bbebb",
        },
        {
          dataKey: "IDR",
          code: "id-ID",
          value: "IDR",
          value1: null,
          remark: null,
          id: 29,
          objId: "a943933be49811ebb5a01866da5bbebb",
        },
        {
          dataKey: "IDR",
          code: "hi-IN",
          value: "IDR",
          value1: null,
          remark: null,
          id: 30,
          objId: "a943d8bce49811ebb5a01866da5bbebb",
        },
      ],
      exchangeRate: "15755.8",
      exchangeRateY: 15755.8,
      isDefault: false,
      createTime: "2021-07-14 07:43:09",
      cultureCode: "id-ID",
      gameCredit: 0.0,
      status: true,
      isShow: true,
      id: 5,
      objId: "a9423905e49811ebb5a01866da5bbebb",
    },
    {
      code: "INR",
      symbol: "₹",
      denomination: "",
      name: "印度卢比",
      nameList: [
        {
          dataKey: "INR",
          code: "zh-CN",
          value: "印度卢比",
          value1: null,
          remark: null,
          id: 31,
          objId: "a9445f29e49811ebb5a01866da5bbebb",
        },
        {
          dataKey: "INR",
          code: "en-US",
          value: "INR",
          value1: null,
          remark: null,
          id: 32,
          objId: "a944a4a7e49811ebb5a01866da5bbebb",
        },
        {
          dataKey: "INR",
          code: "vi-VN",
          value: "INR",
          value1: null,
          remark: null,
          id: 33,
          objId: "a944ee83e49811ebb5a01866da5bbebb",
        },
        {
          dataKey: "INR",
          code: "th-TH",
          value: "INR",
          value1: null,
          remark: null,
          id: 34,
          objId: "a94532a0e49811ebb5a01866da5bbebb",
        },
        {
          dataKey: "INR",
          code: "id-ID",
          value: "INR",
          value1: null,
          remark: null,
          id: 35,
          objId: "a945755be49811ebb5a01866da5bbebb",
        },
        {
          dataKey: "INR",
          code: "hi-IN",
          value: "INR",
          value1: null,
          remark: null,
          id: 36,
          objId: "a945b9cae49811ebb5a01866da5bbebb",
        },
      ],
      exchangeRate: "83.1164",
      exchangeRateY: 83.1164,
      isDefault: false,
      createTime: "2021-07-14 07:43:09",
      cultureCode: "hi-IN",
      gameCredit: 0.0,
      status: true,
      isShow: true,
      id: 6,
      objId: "a94419e6e49811ebb5a01866da5bbebb",
    },
  ],
};

export const Games = {
  success: true,
  errorCode: null,
  message: null,
  total: null,
  data: {
    paged: {
      pageCount: 1,
      pageIndex: 1,
      pageSize: 1000,
      totalCount: 12,
      lastPageIndex: 0,
      previousPageIndex: 0,
      nextPageIndex: -1,
      isFirstPage: false,
      isLastPage: false,
      isMiddlePage: true,
      isNextPageAvailable: false,
      isPreviousPageAvailable: true,
    },
    items: [
      {
        gameName: "香港六合彩",
        gameCode: "lhc",
        platformCode: "SGLottery",
        categoryCode: "cp",
        imageName: "lhc.png",
        tag: "hot",
        isFavorites: false,
      },
      {
        gameName: "澳门六合彩",
        gameCode: "amlhc",
        platformCode: "SGLottery",
        categoryCode: "cp",
        imageName: "amlhc.png",
        tag: "hot",
        isFavorites: false,
      },
      {
        gameName: "极速鱼虾蟹",
        gameCode: "jsYxx",
        platformCode: "SGLottery",
        categoryCode: "cp",
        imageName: "jsYxx.png",
        tag: "hot",
        isFavorites: false,
      },
      {
        gameName: "BTi体育",
        gameCode: "ty",
        platformCode: "bti",
        categoryCode: "ty",
        imageName: "bti_ty.png",
        tag: "hot",
        isFavorites: false,
      },
      {
        gameName: "CQ9 真人",
        gameCode: "CA01",
        platformCode: "cq9",
        categoryCode: "sx",
        imageName: "cq9_sx.png",
        tag: "hot",
        isFavorites: false,
      },
      {
        gameName: "沙巴 电竞",
        gameCode: "ESports",
        platformCode: "ibc",
        categoryCode: "dj",
        imageName: "ibc_ESports.png",
        tag: "hot",
        isFavorites: false,
      },
      {
        gameName: "BTi 电竞",
        gameCode: "ESports",
        platformCode: "bti",
        categoryCode: "dj",
        imageName: "bti_ESports.png",
        tag: "hot",
        isFavorites: false,
      },
      {
        gameName: "S128",
        gameCode: "sea",
        platformCode: "sea",
        categoryCode: "douji",
        imageName: "sea.png",
        tag: "hot",
        isFavorites: false,
      },
      {
        gameName: "PM 彩票",
        gameCode: "pm",
        platformCode: "pm",
        categoryCode: "cp",
        imageName: "pm.png",
        tag: "hot",
        isFavorites: false,
      },
      {
        gameName: "沙巴体育",
        gameCode: "ty",
        platformCode: "ibc",
        categoryCode: "ty",
        imageName: "ibc_ty.png",
        tag: "hot",
        isFavorites: false,
      },
      {
        gameName: "BBIN 真人",
        gameCode: "live",
        platformCode: "bbin",
        categoryCode: "sx",
        imageName: "bbin_sx.png",
        tag: "hot",
        isFavorites: false,
      },
      {
        gameName: "BBIN 体育",
        gameCode: "sport",
        platformCode: "bbin",
        categoryCode: "ty",
        imageName: "bbin_ty.png",
        tag: "hot",
        isFavorites: false,
      },
      {
        gameName: "炸金花",
        gameCode: "220",
        platformCode: "ky",
        categoryCode: "qp",
        imageName: "zh-CN/220.png",
        tag: "hot",
        isFavorites: true,
      },
      {
        gameName: "GW 彩票",
        gameCode: "gw",
        platformCode: "gw",
        categoryCode: "cp",
        imageName: "gw.png",
        tag: "hot",
        isFavorites: false,
      },
      {
        gameName: "ON 真人",
        gameCode: "onbet",
        platformCode: "onbet",
        categoryCode: "sx",
        imageName: "onbet_sx.png",
        tag: "hot",
        isFavorites: false,
      },
    ],
    totalData: null,
  },
};

export const save_totalData = {
  hot: {
    name: "热门",
    games: [
      {
        gameName: "香港六合彩",
        gameCode: "lhc",
        platformCode: "SGLottery",
        categoryCode: "cp",
        imageName: "lhc.png",
        tag: "hot",
        isFavorites: false,
      },
      {
        gameName: "澳门六合彩",
        gameCode: "amlhc",
        platformCode: "SGLottery",
        categoryCode: "cp",
        imageName: "amlhc.png",
        tag: "hot",
        isFavorites: false,
      },
      {
        gameName: "极速鱼虾蟹",
        gameCode: "jsYxx",
        platformCode: "SGLottery",
        categoryCode: "cp",
        imageName: "jsYxx.png",
        tag: "hot",
        isFavorites: false,
      },
      {
        gameName: "BTi体育",
        gameCode: "ty",
        platformCode: "bti",
        categoryCode: "ty",
        imageName: "bti_ty.png",
        tag: "hot",
        isFavorites: false,
      },
      {
        gameName: "CQ9 真人",
        gameCode: "CA01",
        platformCode: "cq9",
        categoryCode: "sx",
        imageName: "cq9_sx.png",
        tag: "hot",
        isFavorites: false,
      },
      {
        gameName: "沙巴 电竞",
        gameCode: "ESports",
        platformCode: "ibc",
        categoryCode: "dj",
        imageName: "ibc_ESports.png",
        tag: "hot",
        isFavorites: false,
      },
      {
        gameName: "BTi 电竞",
        gameCode: "ESports",
        platformCode: "bti",
        categoryCode: "dj",
        imageName: "bti_ESports.png",
        tag: "hot",
        isFavorites: false,
      },
      {
        gameName: "S128",
        gameCode: "sea",
        platformCode: "sea",
        categoryCode: "douji",
        imageName: "sea.png",
        tag: "hot",
        isFavorites: false,
      },
      {
        gameName: "PM 彩票",
        gameCode: "pm",
        platformCode: "pm",
        categoryCode: "cp",
        imageName: "pm.png",
        tag: "hot",
        isFavorites: false,
      },
      {
        gameName: "沙巴体育",
        gameCode: "ty",
        platformCode: "ibc",
        categoryCode: "ty",
        imageName: "ibc_ty.png",
        tag: "hot",
        isFavorites: false,
      },
      {
        gameName: "BBIN 真人",
        gameCode: "live",
        platformCode: "bbin",
        categoryCode: "sx",
        imageName: "bbin_sx.png",
        tag: "hot",
        isFavorites: false,
      },
      {
        gameName: "BBIN 体育",
        gameCode: "sport",
        platformCode: "bbin",
        categoryCode: "ty",
        imageName: "bbin_ty.png",
        tag: "hot",
        isFavorites: false,
      },
      {
        gameName: "炸金花",
        gameCode: "220",
        platformCode: "ky",
        categoryCode: "qp",
        imageName: "zh-CN/220.png",
        tag: "hot",
        isFavorites: true,
      },
      {
        gameName: "GW 彩票",
        gameCode: "gw",
        platformCode: "gw",
        categoryCode: "cp",
        imageName: "gw.png",
        tag: "hot",
        isFavorites: false,
      },
      {
        gameName: "ON 真人",
        gameCode: "onbet",
        platformCode: "onbet",
        categoryCode: "sx",
        imageName: "onbet_sx.png",
        tag: "hot",
        isFavorites: false,
      },
    ],
    platformCode: "hot",
  },
  cp: {
    name: "彩票游戏",
    games: {
      data: {
        success: true,
        errorCode: null,
        message: "cp",
        total: null,
        data: [
          {
            platformName: "天游彩票",
            platformCode: "SGLottery",
            gameCode: "SGLottery",
            gameName: "天游彩票",
            imageName: "SGLottery.png",
            tag: "",
            hasGameItems: false,
          },
          {
            platformName: "GW",
            platformCode: "gw",
            gameCode: "gw",
            gameName: "GW 彩票",
            imageName: "gw.png",
            tag: "cp",
            hasGameItems: false,
          },
          {
            platformName: "PM",
            platformCode: "pm",
            gameCode: "pm",
            gameName: "PM 彩票",
            imageName: "pm.png",
            tag: "cp",
            hasGameItems: false,
          },
          {
            platformName: "ROBO彩票",
            platformCode: "robocp",
            gameCode: "lobby",
            gameName: "ROBO彩票",
            imageName: "robocp_cp.png",
            tag: "cp",
            hasGameItems: false,
          },
        ],
      },
      status: 200,
      statusText: "OK",
      headers: {
        connection: "close",
        "content-length": "661",
        "content-type": "application/json; charset=utf-8",
        date: "Sun, 28 Jan 2024 09:20:11 GMT",
        server: "SK",
        "x-powered-by": "Express",
      },
      config: {
        url: "/api/Game/GamePlatforms?categoryCode=cp&source=1",
        method: "get",
        headers: {
          Accept: "application/json, text/plain, */*",
          Culture: "zh-CN",
          clientType: 2,
        },
        transformRequest: [null],
        transformResponse: [null],
        timeout: 5000,
        xsrfCookieName: "XSRF-TOKEN",
        xsrfHeaderName: "X-XSRF-TOKEN",
        maxContentLength: -1,
        maxBodyLength: -1,
      },
      request: {},
    },
    platformCode: "cp",
  },
  sx: {
    name: "真人视讯",
    games: {
      data: {
        success: true,
        errorCode: null,
        message: "sx",
        total: null,
        data: [
          {
            platformName: "AE2",
            platformCode: "ae2",
            gameCode: "MX-LIVE-001",
            gameName: "AE 真人",
            imageName: "ae_sx.png",
            tag: "sx",
            hasGameItems: false,
          },
          {
            platformName: "WE",
            platformCode: "we",
            gameCode: "we",
            gameName: "WE 真人",
            imageName: "we_sx.png",
            tag: "sx",
            hasGameItems: false,
          },
          {
            platformName: "VIA",
            platformCode: "via",
            gameCode: "live",
            gameName: "VIA 真人",
            imageName: "via_sx.png",
            tag: "sx",
            hasGameItems: false,
          },
          {
            platformName: "BBIN",
            platformCode: "bbin",
            gameCode: "live",
            gameName: "BBIN 真人",
            imageName: "bbin_sx.png",
            tag: "sx",
            hasGameItems: false,
          },
          {
            platformName: "DG",
            platformCode: "dg",
            gameCode: "dg",
            gameName: "DG 真人",
            imageName: "dg_sx.png",
            tag: "sx",
            hasGameItems: false,
          },
          {
            platformName: "ONBET",
            platformCode: "onbet",
            gameCode: "onbet",
            gameName: "ON 真人",
            imageName: "onbet_sx.png",
            tag: "sx",
            hasGameItems: false,
          },
          {
            platformName: "MG",
            platformCode: "mg",
            gameCode: "SMG_titaniumLiveGames_Baccarat",
            gameName: "MG真人",
            imageName: "mg_sx.png",
            tag: "sx",
            hasGameItems: false,
          },
          {
            platformName: "TTG",
            platformCode: "ttg",
            gameCode: "17600",
            gameName: "Swintt 视讯",
            imageName: "ttg_sx.png",
            tag: "dz",
            hasGameItems: false,
          },
          {
            platformName: "WM",
            platformCode: "wm",
            gameCode: "wm",
            gameName: "WM 真人",
            imageName: "wm_sx.png",
            tag: "sx",
            hasGameItems: false,
          },
          {
            platformName: "PT",
            platformCode: "pt",
            gameCode: "bs_bal",
            gameName: "PT真人",
            imageName: "pt_sx.png",
            tag: "dz",
            hasGameItems: false,
          },
          {
            platformName: "CQ9",
            platformCode: "cq9",
            gameCode: "CA01",
            gameName: "CQ9 真人",
            imageName: "cq9_sx.png",
            tag: "dz",
            hasGameItems: false,
          },
          {
            platformName: "SA",
            platformCode: "sa",
            gameCode: "lobby",
            gameName: "SA Live",
            imageName: "sa_sx.png",
            tag: "sx",
            hasGameItems: false,
          },
          {
            platformName: "EVO",
            platformCode: "evo",
            gameCode: "lobby",
            gameName: "EVO真人",
            imageName: "evo_sx.png",
            tag: "sx",
            hasGameItems: false,
          },
          {
            platformName: "AG",
            platformCode: "ag",
            gameCode: "18",
            gameName: "AG 真人",
            imageName: "ag_sx.png",
            tag: "sx",
            hasGameItems: false,
          },
        ],
      },
      status: 200,
      statusText: "OK",
      headers: {
        connection: "close",
        "content-encoding": "gzip",
        "content-type": "application/json; charset=utf-8",
        date: "Sun, 28 Jan 2024 09:20:11 GMT",
        server: "SK",
        "transfer-encoding": "chunked",
        vary: "Accept-Encoding",
        "x-powered-by": "Express",
      },
      config: {
        url: "/api/Game/GamePlatforms?categoryCode=sx&source=1",
        method: "get",
        headers: {
          Accept: "application/json, text/plain, */*",
          Culture: "zh-CN",
          clientType: 2,
        },
        transformRequest: [null],
        transformResponse: [null],
        timeout: 5000,
        xsrfCookieName: "XSRF-TOKEN",
        xsrfHeaderName: "X-XSRF-TOKEN",
        maxContentLength: -1,
        maxBodyLength: -1,
      },
      request: {},
    },
    platformCode: "sx",
  },
  ty: {
    name: "体育游戏",
    games: {
      data: {
        success: true,
        errorCode: null,
        message: "ty",
        total: null,
        data: [
          {
            platformName: "BBIN",
            platformCode: "bbin",
            gameCode: "sport",
            gameName: "BBIN 体育",
            imageName: "bbin_ty.png",
            tag: "sx",
            hasGameItems: false,
          },
          {
            platformName: "BTi",
            platformCode: "bti",
            gameCode: "ty",
            gameName: "BTi体育",
            imageName: "bti_ty.png",
            tag: "ty",
            hasGameItems: false,
          },
          {
            platformName: "CMD",
            platformCode: "cmd",
            gameCode: "cmd",
            gameName: "CMD体育",
            imageName: "cmd.png",
            tag: "ty",
            hasGameItems: false,
          },
          {
            platformName: "UG",
            platformCode: "ug",
            gameCode: "ug",
            gameName: "UG 体育",
            imageName: "ug_ty.png",
            tag: "ty",
            hasGameItems: false,
          },
          {
            platformName: "沙巴",
            platformCode: "ibc",
            gameCode: "ty",
            gameName: "沙巴体育",
            imageName: "ibc_ty.png",
            tag: "ty",
            hasGameItems: false,
          },
          {
            platformName: "SBO",
            platformCode: "sbo",
            gameCode: "SportsBook",
            gameName: "SBO体育",
            imageName: "SportsBook.png",
            tag: "ty",
            hasGameItems: false,
          },
        ],
      },
      status: 200,
      statusText: "OK",
      headers: {
        connection: "close",
        "content-length": "931",
        "content-type": "application/json; charset=utf-8",
        date: "Sun, 28 Jan 2024 09:20:11 GMT",
        server: "SK",
        "x-powered-by": "Express",
      },
      config: {
        url: "/api/Game/GamePlatforms?categoryCode=ty&source=1",
        method: "get",
        headers: {
          Accept: "application/json, text/plain, */*",
          Culture: "zh-CN",
          clientType: 2,
        },
        transformRequest: [null],
        transformResponse: [null],
        timeout: 5000,
        xsrfCookieName: "XSRF-TOKEN",
        xsrfHeaderName: "X-XSRF-TOKEN",
        maxContentLength: -1,
        maxBodyLength: -1,
      },
      request: {},
    },
    platformCode: "ty",
  },
  qp: {
    name: "棋牌游戏",
    games: {
      data: {
        success: true,
        errorCode: null,
        message: "qp",
        total: null,
        data: [
          {
            platformName: "AE2",
            platformCode: "ae2",
            gameCode: null,
            gameName: null,
            imageName: "ae2",
            tag: "sx",
            hasGameItems: true,
          },
          {
            platformName: "PP",
            platformCode: "pp",
            gameCode: null,
            gameName: null,
            imageName: "pp",
            tag: "dz",
            hasGameItems: true,
          },
          {
            platformName: "开元",
            platformCode: "ky",
            gameCode: null,
            gameName: null,
            imageName: "ky",
            tag: "qp",
            hasGameItems: true,
          },
          {
            platformName: "MG",
            platformCode: "mg",
            gameCode: null,
            gameName: null,
            imageName: "mg",
            tag: "sx",
            hasGameItems: true,
          },
          {
            platformName: "乐博棋牌",
            platformCode: "rbqp",
            gameCode: null,
            gameName: null,
            imageName: "rbqp",
            tag: "qp",
            hasGameItems: true,
          },
          {
            platformName: "CQ9",
            platformCode: "cq9",
            gameCode: null,
            gameName: null,
            imageName: "cq9",
            tag: "dz",
            hasGameItems: true,
          },
          {
            platformName: "FG",
            platformCode: "fg",
            gameCode: null,
            gameName: null,
            imageName: "fg",
            tag: "dz",
            hasGameItems: true,
          },
          {
            platformName: "JDB",
            platformCode: "jdb",
            gameCode: null,
            gameName: null,
            imageName: "jdb",
            tag: "dz",
            hasGameItems: true,
          },
          {
            platformName: "MW",
            platformCode: "mw",
            gameCode: null,
            gameName: null,
            imageName: "mw",
            tag: "dz",
            hasGameItems: true,
          },
          {
            platformName: "V8 Poker",
            platformCode: "v8",
            gameCode: null,
            gameName: null,
            imageName: "v8",
            tag: "qp",
            hasGameItems: true,
          },
          {
            platformName: "吉利",
            platformCode: "jl",
            gameCode: null,
            gameName: null,
            imageName: "jl",
            tag: "dz",
            hasGameItems: true,
          },
          {
            platformName: "乐游",
            platformCode: "leg",
            gameCode: null,
            gameName: null,
            imageName: "leg",
            tag: "qp",
            hasGameItems: true,
          },
        ],
      },
      status: 200,
      statusText: "OK",
      headers: {
        connection: "close",
        "content-encoding": "gzip",
        "content-type": "application/json; charset=utf-8",
        date: "Sun, 28 Jan 2024 09:20:11 GMT",
        server: "SK",
        "transfer-encoding": "chunked",
        vary: "Accept-Encoding",
        "x-powered-by": "Express",
      },
      config: {
        url: "/api/Game/GamePlatforms?categoryCode=qp&source=1",
        method: "get",
        headers: {
          Accept: "application/json, text/plain, */*",
          Culture: "zh-CN",
          clientType: 2,
        },
        transformRequest: [null],
        transformResponse: [null],
        timeout: 5000,
        xsrfCookieName: "XSRF-TOKEN",
        xsrfHeaderName: "X-XSRF-TOKEN",
        maxContentLength: -1,
        maxBodyLength: -1,
      },
      request: {},
    },
    platformCode: "qp",
  },
  by: {
    name: "捕鱼游戏",
    games: {
      data: {
        success: true,
        errorCode: null,
        message: "by",
        total: null,
        data: [
          {
            platformName: "BBIN",
            platformCode: "bbin",
            gameCode: null,
            gameName: null,
            imageName: "bbin",
            tag: "sx",
            hasGameItems: true,
          },
          {
            platformName: "开元",
            platformCode: "ky",
            gameCode: null,
            gameName: null,
            imageName: "ky",
            tag: "qp",
            hasGameItems: true,
          },
          {
            platformName: "MG",
            platformCode: "mg",
            gameCode: null,
            gameName: null,
            imageName: "mg",
            tag: "sx",
            hasGameItems: true,
          },
          {
            platformName: "乐博棋牌",
            platformCode: "rbqp",
            gameCode: null,
            gameName: null,
            imageName: "rbqp",
            tag: "qp",
            hasGameItems: true,
          },
          {
            platformName: "CQ9",
            platformCode: "cq9",
            gameCode: null,
            gameName: null,
            imageName: "cq9",
            tag: "dz",
            hasGameItems: true,
          },
          {
            platformName: "FG",
            platformCode: "fg",
            gameCode: null,
            gameName: null,
            imageName: "fg",
            tag: "dz",
            hasGameItems: true,
          },
          {
            platformName: "JDB",
            platformCode: "jdb",
            gameCode: null,
            gameName: null,
            imageName: "jdb",
            tag: "dz",
            hasGameItems: true,
          },
          {
            platformName: "MW",
            platformCode: "mw",
            gameCode: null,
            gameName: null,
            imageName: "mw",
            tag: "dz",
            hasGameItems: true,
          },
          {
            platformName: "GNS",
            platformCode: "gns",
            gameCode: null,
            gameName: null,
            imageName: "gns",
            tag: "dz",
            hasGameItems: true,
          },
          {
            platformName: "AG",
            platformCode: "ag",
            gameCode: null,
            gameName: null,
            imageName: "ag",
            tag: "sx",
            hasGameItems: true,
          },
          {
            platformName: "吉利",
            platformCode: "jl",
            gameCode: null,
            gameName: null,
            imageName: "jl",
            tag: "dz",
            hasGameItems: true,
          },
          {
            platformName: "乐游",
            platformCode: "leg",
            gameCode: null,
            gameName: null,
            imageName: "leg",
            tag: "qp",
            hasGameItems: true,
          },
        ],
      },
      status: 200,
      statusText: "OK",
      headers: {
        connection: "close",
        "content-encoding": "gzip",
        "content-type": "application/json; charset=utf-8",
        date: "Sun, 28 Jan 2024 09:20:11 GMT",
        server: "SK",
        "transfer-encoding": "chunked",
        vary: "Accept-Encoding",
        "x-powered-by": "Express",
      },
      config: {
        url: "/api/Game/GamePlatforms?categoryCode=by&source=1",
        method: "get",
        headers: {
          Accept: "application/json, text/plain, */*",
          Culture: "zh-CN",
          clientType: 2,
        },
        transformRequest: [null],
        transformResponse: [null],
        timeout: 5000,
        xsrfCookieName: "XSRF-TOKEN",
        xsrfHeaderName: "X-XSRF-TOKEN",
        maxContentLength: -1,
        maxBodyLength: -1,
      },
      request: {},
    },
    platformCode: "by",
  },
  dz: {
    name: "电子游艺",
    games: {
      data: {
        success: true,
        errorCode: null,
        message: "dz",
        total: null,
        data: [
          {
            platformName: "BBIN",
            platformCode: "bbin",
            gameCode: null,
            gameName: null,
            imageName: "bbin",
            tag: "sx",
            hasGameItems: true,
          },
          {
            platformName: "PG",
            platformCode: "pg",
            gameCode: null,
            gameName: null,
            imageName: "pg",
            tag: "dz",
            hasGameItems: true,
          },
          {
            platformName: "PP",
            platformCode: "pp",
            gameCode: null,
            gameName: null,
            imageName: "pp",
            tag: "dz",
            hasGameItems: true,
          },
          {
            platformName: "开元",
            platformCode: "ky",
            gameCode: null,
            gameName: null,
            imageName: "ky",
            tag: "qp",
            hasGameItems: true,
          },
          {
            platformName: "MG",
            platformCode: "mg",
            gameCode: null,
            gameName: null,
            imageName: "mg",
            tag: "sx",
            hasGameItems: true,
          },
          {
            platformName: "TTG",
            platformCode: "ttg",
            gameCode: null,
            gameName: null,
            imageName: "ttg",
            tag: "dz",
            hasGameItems: true,
          },
          {
            platformName: "乐博棋牌",
            platformCode: "rbqp",
            gameCode: null,
            gameName: null,
            imageName: "rbqp",
            tag: "qp",
            hasGameItems: true,
          },
          {
            platformName: "PT",
            platformCode: "pt",
            gameCode: null,
            gameName: null,
            imageName: "pt",
            tag: "dz",
            hasGameItems: true,
          },
          {
            platformName: "CQ9",
            platformCode: "cq9",
            gameCode: null,
            gameName: null,
            imageName: "cq9",
            tag: "dz",
            hasGameItems: true,
          },
          {
            platformName: "FG",
            platformCode: "fg",
            gameCode: null,
            gameName: null,
            imageName: "fg",
            tag: "dz",
            hasGameItems: true,
          },
          {
            platformName: "JDB",
            platformCode: "jdb",
            gameCode: null,
            gameName: null,
            imageName: "jdb",
            tag: "dz",
            hasGameItems: true,
          },
          {
            platformName: "MW",
            platformCode: "mw",
            gameCode: null,
            gameName: null,
            imageName: "mw",
            tag: "dz",
            hasGameItems: true,
          },
          {
            platformName: "GNS",
            platformCode: "gns",
            gameCode: null,
            gameName: null,
            imageName: "gns",
            tag: "dz",
            hasGameItems: true,
          },
          {
            platformName: "AG",
            platformCode: "ag",
            gameCode: null,
            gameName: null,
            imageName: "ag",
            tag: "sx",
            hasGameItems: true,
          },
          {
            platformName: "吉利",
            platformCode: "jl",
            gameCode: null,
            gameName: null,
            imageName: "jl",
            tag: "dz",
            hasGameItems: true,
          },
          {
            platformName: "乐游",
            platformCode: "leg",
            gameCode: null,
            gameName: null,
            imageName: "leg",
            tag: "qp",
            hasGameItems: true,
          },
        ],
      },
      status: 200,
      statusText: "OK",
      headers: {
        connection: "close",
        "content-encoding": "gzip",
        "content-type": "application/json; charset=utf-8",
        date: "Sun, 28 Jan 2024 09:20:11 GMT",
        server: "SK",
        "transfer-encoding": "chunked",
        vary: "Accept-Encoding",
        "x-powered-by": "Express",
      },
      config: {
        url: "/api/Game/GamePlatforms?categoryCode=dz&source=1",
        method: "get",
        headers: {
          Accept: "application/json, text/plain, */*",
          Culture: "zh-CN",
          clientType: 2,
        },
        transformRequest: [null],
        transformResponse: [null],
        timeout: 5000,
        xsrfCookieName: "XSRF-TOKEN",
        xsrfHeaderName: "X-XSRF-TOKEN",
        maxContentLength: -1,
        maxBodyLength: -1,
      },
      request: {},
    },
    platformCode: "dz",
  },
  dj: {
    name: "电竞游戏",
    games: {
      data: {
        success: true,
        errorCode: null,
        message: "dj",
        total: null,
        data: [
          {
            platformName: "AE2",
            platformCode: "ae2",
            gameCode: "E1-ESPORTS-001",
            gameName: "AE 电竞",
            imageName: "ae_dj1.png",
            tag: "sx",
            hasGameItems: false,
          },
          {
            platformName: "BTi",
            platformCode: "bti",
            gameCode: "ESports",
            gameName: "BTi 电竞",
            imageName: "bti_ESports.png",
            tag: "ty",
            hasGameItems: false,
          },
          {
            platformName: "沙巴",
            platformCode: "ibc",
            gameCode: "ESports",
            gameName: "沙巴 电竞",
            imageName: "ibc_ESports.png",
            tag: "ty",
            hasGameItems: false,
          },
        ],
      },
      status: 200,
      statusText: "OK",
      headers: {
        connection: "close",
        "content-length": "530",
        "content-type": "application/json; charset=utf-8",
        date: "Sun, 28 Jan 2024 09:20:12 GMT",
        server: "SK",
        "x-powered-by": "Express",
      },
      config: {
        url: "/api/Game/GamePlatforms?categoryCode=dj&source=1",
        method: "get",
        headers: {
          Accept: "application/json, text/plain, */*",
          Culture: "zh-CN",
          clientType: 2,
        },
        transformRequest: [null],
        transformResponse: [null],
        timeout: 5000,
        xsrfCookieName: "XSRF-TOKEN",
        xsrfHeaderName: "X-XSRF-TOKEN",
        maxContentLength: -1,
        maxBodyLength: -1,
      },
      request: {},
    },
    platformCode: "dj",
  },
  douji: {
    name: "斗鸡游戏",
    games: {
      data: {
        success: true,
        errorCode: null,
        message: "douji",
        total: null,
        data: [
          {
            platformName: "AE2",
            platformCode: "ae2",
            gameCode: "SV-LIVE-001",
            gameName: "SV388",
            imageName: "ae_douji.png",
            tag: "sx",
            hasGameItems: false,
          },
          {
            platformName: "SEA Gaming",
            platformCode: "sea",
            gameCode: "sea",
            gameName: "S128",
            imageName: "sea.png",
            tag: "douji",
            hasGameItems: false,
          },
        ],
      },
      status: 200,
      statusText: "OK",
      headers: {
        connection: "close",
        "content-length": "363",
        "content-type": "application/json; charset=utf-8",
        date: "Sun, 28 Jan 2024 09:20:12 GMT",
        server: "SK",
        "x-powered-by": "Express",
      },
      config: {
        url: "/api/Game/GamePlatforms?categoryCode=douji&source=1",
        method: "get",
        headers: {
          Accept: "application/json, text/plain, */*",
          Culture: "zh-CN",
          clientType: 2,
        },
        transformRequest: [null],
        transformResponse: [null],
        timeout: 5000,
        xsrfCookieName: "XSRF-TOKEN",
        xsrfHeaderName: "X-XSRF-TOKEN",
        maxContentLength: -1,
        maxBodyLength: -1,
      },
      request: {},
    },
    platformCode: "douji",
  },
};

export const GetActivityGroups = {
    "success": true,
    "errorCode": null,
    "message": null,
    "total": null,
    "data": [
        {
            "objId": "8",
            "groupName": "新人专场",
            "icon": "/file/DEVGJ/2023/5/24/SOrjqQLQVcqThSAmJ9i.png",
            "tagClass": null,
            "isActive": false
        },
        {
            "objId": "9",
            "groupName": "USDT优惠",
            "icon": "/file/DEVGJ/2023/5/25/fmQNLvsJ7hJ79iWdDVB.jpeg",
            "tagClass": null,
            "isActive": false
        },
        {
            "objId": "2",
            "groupName": "体育优惠",
            "icon": "/file/DEVGJ/2023/5/25/hyqUbPcfkTiL8H7Eyeb.png",
            "tagClass": null,
            "isActive": false
        },
        {
            "objId": "1",
            "groupName": "彩票优惠",
            "icon": "/file/DEVGJ/2023/5/25/0Au4h3oNh9rCRX6VFbk.jpg",
            "tagClass": null,
            "isActive": false
        },
        {
            "objId": "6",
            "groupName": "电子优惠",
            "icon": "/file/DEVGJ/2023/5/25/zU4Qa7V9XV83p0y4EiX.png",
            "tagClass": null,
            "isActive": false
        },
        {
            "objId": "5",
            "groupName": "棋牌优惠",
            "icon": "/file/DEVGJ/2023/5/25/YlfC2exZjsxj8xFdaPK.png",
            "tagClass": null,
            "isActive": false
        },
        {
            "objId": "3",
            "groupName": "电竞优惠",
            "icon": "/file/DEVGJ/2023/5/25/o6O1KHyklU9x3FVA43S.jpeg",
            "tagClass": null,
            "isActive": false
        },
        {
            "objId": "4",
            "groupName": "真人优惠",
            "icon": "/file/DEVGJ/2023/5/25/feWqqyRrTwQxgY0piYs.png",
            "tagClass": null,
            "isActive": false
        },
        {
            "objId": "10",
            "groupName": "其他",
            "icon": "/file/DEVGJ/2023/5/25/yB4r8PyeiyisWqdyxyJ.jpg",
            "tagClass": null,
            "isActive": false
        }
    ]
}

export const GetActivityList = {
    "success": true,
    "errorCode": null,
    "message": null,
    "total": null,
    "data": {
        "paged": {
            "pageCount": 1,
            "pageIndex": 1,
            "pageSize": 10,
            "totalCount": 5,
            "lastPageIndex": 0,
            "previousPageIndex": 0,
            "nextPageIndex": -1,
            "isFirstPage": false,
            "isLastPage": false,
            "isMiddlePage": true,
            "isNextPageAvailable": false,
            "isPreviousPageAvailable": true
        },
        "items": [
            {
                "objId": "5c0d6a0b59c24278a13d591d32b4b8cc",
                "tagClass": null,
                "title": "测试2",
                "bannerImg": "/file/DEVGJ/2023/12/7/dyh3re05yHRpiZRPRfx.png",
                "startTime": null,
                "endTime": null,
                "lowestVip": 1,
                "updateTime": "2023-12-16 07:03:29"
            },
            {
                "objId": "aa502982d11f4b92868b7744b5bdd39f",
                "tagClass": null,
                "title": "测试3",
                "bannerImg": "/file/DEVGJ/2023/12/7/jr0WYB3l2z8tGwIoSs9.png",
                "startTime": null,
                "endTime": null,
                "lowestVip": 1,
                "updateTime": "2023-12-16 07:03:19"
            },
            {
                "objId": "396488bbfa3a45a3ba57a517cfdd46ea",
                "tagClass": null,
                "title": "测试5",
                "bannerImg": "/file/DEVGJ/2023/12/7/1S3pMKGU1LrjZc4T27g.jpg",
                "startTime": null,
                "endTime": null,
                "lowestVip": 1,
                "updateTime": "2023-12-16 07:03:08"
            },
            {
                "objId": "1d6896ec31d6437b932e3f710d3254f2",
                "tagClass": null,
                "title": "测试6",
                "bannerImg": "/file/DEVGJ/2023/12/7/zjSfV0SwLFohZRT8Jx7.jpg",
                "startTime": null,
                "endTime": null,
                "lowestVip": 1,
                "updateTime": "2023-12-16 07:02:55"
            },
            {
                "objId": "51cdee6ebb9f493db322ec32dcc07cbc",
                "tagClass": null,
                "title": "测试1",
                "bannerImg": "/file/DEVGJ/2023/12/13/RTFbHpa0hnmkG2lu8sm.jpg",
                "startTime": null,
                "endTime": null,
                "lowestVip": 1,
                "updateTime": "2024-01-03 21:58:06"
            }
        ],
        "totalData": null
    }
}

export const Login = {
    "success": true,
    "errorCode": null,
    "message": null,
    "total": null,
    "data": {
        "memberAccount": "sam123456",
        "memberName": "123",
        "popularizeId": 1723555,
        "avatar": "08",
        "nickName": "123",
        "balance": 4549.43,
        "loginTime": "2024-01-28 05:33:39",
        "regTime": "2022-02-22 04:49:49",
        "email": "",
        "isEmailVerified": false,
        "wechat": "1111",
        "birthday": "1956-10-02",
        "tel": "86-",
        "isTelVerified": false,
        "qq": "123",
        "memberType": 0,
        "level": 4,
        "vipLevel": 3,
        "vipLevelName": "VIP3",
        "currencyCode": "CNY",
        "currencySymbol": "¥",
        "currencyDenomination": "",
        "currencyName": "人民币",
        "token": "e0d3eac04973473297ae5ce0a6696a1a",
        "isMute": false,
        "isOpenCheckIn": true,
        "isOpenTurntable": true,
        "isOpenTransfer": false,
        "zalo": "",
        "telegram": "",
        "faceBook": null
    }
}

export const CheckLogin = {"success":true,"errorCode":null,"message":null,"total":null,"data":null}

export const GetMemberData = {
    "success": true,
    "errorCode": null,
    "message": null,
    "total": null,
    "data": {
        "memberAccount": "sam123456",
        "avatar": "08",
        "nickname": "123",
        "invitationCode": 1723555,
        "balance": 4549.43,
        "vipLevel": 3,
        "depositRequire": 50000.0,
        "dmlRequire": 300000.0,
        "currentTotalDeposit": 15500.0,
        "regTime": "2022-02-22 04:49:49",
        "currentTotalDml": 310370.0,
        "currencyCode": "CNY",
        "currencySymbol": "¥",
        "memberType": 0,
        "currencyDenomination": ""
    }
}

export const GetUserInfo = {
    "success": true,
    "errorCode": null,
    "message": null,
    "total": null,
    "data": {
        "memberAccount": "sam123456",
        "memberName": "123",
        "popularizeId": 1723555,
        "avatar": "08",
        "nickName": "123",
        "balance": 4549.43,
        "loginTime": "2024-01-28 05:33:40",
        "regTime": "2022-02-22 04:49:49",
        "email": "",
        "isEmailVerified": false,
        "wechat": "1111",
        "birthday": "1956-10-02",
        "tel": "86-",
        "isTelVerified": false,
        "qq": "123",
        "memberType": 0,
        "level": 4,
        "vipLevel": 3,
        "vipLevelName": "VIP3",
        "currencyCode": "CNY",
        "currencySymbol": "¥",
        "currencyDenomination": "",
        "currencyName": "人民币",
        "token": null,
        "isMute": false,
        "isOpenCheckIn": true,
        "isOpenTurntable": true,
        "isOpenTransfer": false,
        "zalo": "",
        "telegram": "",
        "faceBook": null
    }
}

export const Logout = {"success":true,"errorCode":null,"message":null,"total":null,"data":"登出成功"}